language: node_js
node_js: node
before_install:
- export JAVA_HOME=/usr/lib/jvm/java-8-oracle
- export PATH=$JAVA_HOME/bin:$PATH
script:
- npm run test:lint
- 'if [ "$TRAVIS_SECURE_ENV_VARS" = "true" ]; then polymer test --skip-plugin local; fi'
- 'if [ "$TRAVIS_SECURE_ENV_VARS" = "false" ]; then polymer test --skip-plugin sauce; fi'
- 'if [ "$TRAVIS_SECURE_ENV_VARS" = "true" ]; then npm run test:galen:sauce; fi'
addons:
  apt:
    packages:
    - oracle-java8-installer
env:
  global:
  - SAUCE_USERNAME: Desire2Learn
  - secure: e2JomX27Ro3hoO3OYYJdGszdUxZhpwdAo0K3yJpGQkPeaxYhsYmCan9WOGGmcQ5oS79UFIpMl+x0n8fooo2pueCmxpuu61as7nKQ/cbbnwiuFHxx8uu2ETdECqqyY92hcOTw3yxS1jIqJ3rCMWBWBJBLCA7rnWnU0LMt1gYqcEqU1mTgMu6bqEN8SHzjkz2ALmbwKegOr8BNsFtTg563axzAhKn1kA87Bk2BlaKLEHJ1fGSDvgwV7u+THBOX1WlDQCIIKeCDTON+t9+GtjSRN+gT6wVuztyDyLo6x8bth8mMOvUzWvpWdnadXb8U0mmLEB/F8O1DPiGP0Y4NvLctTPFM6zY2le9/XAIWyqXgIaN3WZ8J7pOnn5KHsVxTQFaFPn8M0ddLs6rlMGBQjaF6akCvkVoR90ZMzpylflmTIeopwPYkP+36u5NC6VxS64tn5jCBqOPVgkXkvesyhFPuPwjCTNRQMY632jJQ7rzNfHz3tLlBvNbXO40pFYVexPeTKI3R81w7DtQ9nn0P7/7qSnAwZGh1IUW7dxny+R+tkluH7iEw9+U4awVP/PPGUvAqVYPM8uAWpTrq3Gu+ov3HpCpndvknVj5h3jmVDKA07nWRjeaiOMC9jcqeJA/tkUDzEB1qtEBY6X8b30L4MbryTy7zadvLDv1ItXQlX7t2MLM=
